stages:
  - build

package_build:
  stage: build
  image: alpine:latest
  tags:
    - docker-exec
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - qorus-vscode-*.vsix
    when: on_success
    expire_in: 2 day
  script:
    - apk add git nodejs npm
    - npm -g i vsce
    - npm install
    - npm run build
    - vsce package
