stages:
  - build

package_build:
  stage: build
  image: alpine:latest
  tags:
    - docker-exec
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - qorus-vscode-*.vsix
    when: on_success
    expire_in: 2 day
  script:
    - apk add git nodejs npm
    - npm -g i vsce
    - |
        if [ -e ".gitmodules" ]; then
          git config --file=.gitmodules submodule.qorus-object-parser.url https://${QOP_DEPLOY_TOKEN}:${QOP_DEPLOY_PASS}@git.qoretechnologies.com/qorus/qorus-object-parser.git
          git submodule update --init
        fi
    - npm install
    - npm run build
    - vsce package
